### ISSUE TITLE
feat: QUIT on refactored base

### ISSUE THREAD

**Issue by refigo** [codewhite7777/ft_irc#2]
**Description**
Client에서 오는 QUIT command를 처리하는 기능 추가

**TODO**
- [x] search: QUIT command protocol
https://modern.ircdocs.horse/index.html#quit-message

  The QUIT command is used to terminate a client’s connection to the server. The server acknowledges this by replying with an [ERROR](https://modern.ircdocs.horse/index.html#error-message) message and closing the connection to the client.
  
  Command Example:
  ```
    QUIT :Gone to have lunch         ; Client exiting from the network
  Message Example:
  
    :dan-!d@localhost QUIT :Quit: Bye for now!
                                     ; dan- is exiting the network with
                                     the message: "Quit: Bye for now!"
  ```

- [x]  search: protocol message example(between inspircd and irssi)
  ```
  in tcpflow_
  127.000.000.001.60596-127.000.000.001.06667: QUIT :leaving
  
  127.000.000.001.06667-127.000.000.001.60596: ERROR :Closing link: (root@127.0.0.1) [Quit: leaving]
  
  127.000.000.001.06667-127.000.000.001.60598: :nick1!root@127.0.0.1 QUIT :Quit: leaving
  
  in inspircd(debug mode)_
  Thu Sep 29 2022 09:59:21 USERINPUT: C[811AAAAAA] I QUIT :leaving
  Thu Sep 29 2022 09:59:21 USERS: QuitUser: 811AAAAAA=nick1 'Quit: leaving'
  Thu Sep 29 2022 09:59:21 USEROUTPUT: C[811AAAAAA] O ERROR :Closing link: (root@127.0.0.1) [Quit: leaving]
  Thu Sep 29 2022 09:59:21 USEROUTPUT: C[811AAAAAB] O :nick1!root@127.0.0.1 QUIT :Quit: leaving
  Thu Sep 29 2022 09:59:21 SOCKET: Remove file descriptor: 7
  Thu Sep 29 2022 09:59:21 QUIT: Client exiting: nick1!root@127.0.0.1 (127.0.0.1) [Quit: leaving]
  Thu Sep 29 2022 09:59:21 CULLLIST: Deleting @0xaaaad40755c0
  
  ```

- [x] set: logic
- [x]  implement: QUIT request logic
    - [x]  set: client’s disconnect_flag on
    - [x]  send: closing ERROR message to the user
        
        `ERROR :Closing link: (realname@hostname) [Quit: leaving_message]`
        
        with Protocol.rplErrorClosing()
        
    - [x]  send: the client quitting message to other clients in same channels the client is in
        - [x]  implement: Server.makeOtherClntListInSameChanns()
            - [x]  implement: Channel.makeClntListInChannExceptOne()
        - [x]  send: protocol to each client in loop
            - [x]  send: Protocol.clntQuit() to each client in loop
        
        ```
        두명의 클라이언트가 두개의 채널에 동시에 들어가 있을 때, 한 클라이언트가 QUIT을 하면 다른 클라이언트는 QUIT하는 클라이언트가 나간다는 메시지를 한번만 받는다.
        
        127.000.000.001.60630-127.000.000.001.06667: QUIT :leaving
        127.000.000.001.06667-127.000.000.001.60630: ERROR :Closing link: (root@127.0.0.1) [Quit: leaving]
        127.000.000.001.06667-127.000.000.001.60632: :nick2!root@127.0.0.1 QUIT :Quit: leaving
        
        ```
        
    - [x]  erase: the client in each channels which the client is in.
        - [x]  implement: Server.requestChannsToErase()
            - [x]  implement: Channel.eraseClntIfIs()

    - [x]  test: Command.quit()
